language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        # build dependencies
        apt:
          packages:
            - libboost-python-dev
            - libfreetype6-dev
            - libx11-dev
            - libxinerama-dev
            - libxrandr-dev
            - libxcursor-dev
            - mesa-common-dev
            - libasound2-dev
            - freeglut3-dev
            - libxcomposite-dev
            - libcurl4-gnutls-dev
      install:
        # test dependencies
        - pip install --user --requirement requirements.txt

    - os: osx
      install:
        # build dependencies
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install boost-python
        # test dependencies
        - pip2 install --user --requirement requirements.txt

script:
  - ./build.sh
  - ./test.sh

# improve build speed a bit
git: depth: 3
cache: directories: $HOME/.cache/pip
