language: cpp
compiler: clang
os:
  - linux
#  - osx

sudo: true

# Linux dependencies
addons:
  apt:
    packages:
      # build dependencies
      - libboost-python-dev
      - libfreetype6-dev
      - libx11-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxcursor-dev
      - mesa-common-dev
      - libasound2-dev
      - freeglut3-dev
      - libxcomposite-dev
      - libcurl4-gnutls-dev
      # for analysing core dumps in 'after_failure'
      - gdb

install:
  # OSX build dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install boost-python; alias pip=pip2; fi

  # Linux and OSX dependencies (just for integration tests)
  - pip install --user --upgrade pip
  - pip install --user --requirement requirements.txt

cache: pip

script:
  - ulimit -c unlimited  # enable core dumps
  - sudo sysctl -w kernel.core_pattern=core
  - ./build.sh
  - ./test.sh

after_failure:
  # analyse core dumps
  - ls -lR
  - COREFILE=$(find . -maxdepth 2 -name "core*" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then sudo gdb -c "$COREFILE" python -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
