language: cpp
compiler: clang
os:
  - linux
  - osx

# Linux dependencies
addons:
  apt:
    packages:
      - libboost-python-dev
      - libfreetype6-dev
      - libx11-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxcursor-dev
      - mesa-common-dev
      - libasound2-dev
      - freeglut3-dev
      - libxcomposite-dev
      - libcurl4-gnutls-dev

# OSX dependencies  and  Python dependencies (for test)
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install boost-python; fi
  - pip install --user --upgrade pip
  - pip install --user --requirements requirements.txt


script: ./build_and_test.sh
